force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Review_Provided__c.field-meta.xml
<CustomField>
    <fullName>Review_Provided__c</fullName>
    <label>Review Provided</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Enter a 1-5 Rating of candidate.</inlineHelpText>
    <label>Rating</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReviewTriggerHandlerTests.cls
@isTest
public class ReviewTriggerHandlerTests {

    
    
    @isTest
    static void test()
    {
        
        
        
                
          List<Job_Application__c> jobAppList = new  List<Job_Application__c> ();
        
          for(Integer i=1; i<=5 ; i++)
          {
              
             
                  Job_Application__c jobApp = new Job_Application__c();
                  jobApp.Cover_Letter__c = 'Testing' + i;
                  
                  jobAppList.add(jobApp);
          
              
          }
        
        
          
         insert jobAppList;
        
        
        
        
        
        
          List<Review__c> reviewList = new  List<Review__c> ();
        
          for(Job_Application__c jobApp : jobAppList)
          {
              
             
                  Review__c rev = new Review__c();
                  rev.Job_Application__c = jobApp.Id ;
                  rev.Rating__c = 4;
                  reviewList.add(rev);
          
              
          }
        
        
          
         insert reviewList;
        
        
        
        
        
        
         List<Job_Application__c> jobAppList1 = [Select Id,Review_Provided__c From Job_Application__c Where Id  =: jobAppList[0].Id];
         System.AssertEquals('Yes',jobAppList1[0].Review_Provided__c);
          
        
        
        
    }
    
    
    
    
}