force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{0000}</displayFormat>
        <label>Job Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Review_Provided__c.field-meta.xml
<CustomField>
    <fullName>Review_Provided__c</fullName>
    <label>Review Provided</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Review Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <inlineHelpText>Enter a 1-5 Rating of candidate.</inlineHelpText>
    <label>Rating</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ReviewTriggerHandler.cls
public class ReviewTriggerHandler {

    
        public static void updateReviewProvidedField(List<Review__c> reviewList)
    {
        
          List<Job_Application__c> jobAppList = new  List<Job_Application__c> ();
        
          for(Review__c rev: reviewList)
          {
              
              if(rev.Rating__c != null)
              {
                  
                  Job_Application__c jobApp = new Job_Application__c();
                  jobApp.id = rev.Job_Application__c;
                  jobApp.Review_Provided__c = 'Yes';
                  
                  jobAppList.add(jobApp);
              }
              
          }
        
        
          
         update jobAppList;



    }

    
    
}