force-app/main/default/objects/Position__c/fields/Days_Open__c.field-meta.xml
<CustomField>
    <fullName>Days_Open__c</fullName>
    <formula>IF( ISBLANK(Close_Date__c) ,  TODAY() -  Open_Date__c  ,  Close_Date__c  -  Open_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Open</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Filled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public class PositionTriggerHandler {

    
    
    
    
    public static void updateStatusFieldonPosition(List<Position__c> posList)
    {
        
                
                for(Position__c pos : posList)
                {
        
        
                       if(pos.Days_Open__c > 30)
                       {
                           pos.Status__c = 'Closed - Filled';
                       }
                    
                    
                }
        
        
    }
    
    
    
    
    
    
    public static void createRealtedTask(List<Position__c> posList)
    {



        List<task> taskList = new List<task>();

        for(Position__c pos : posList)
        {


               if(pos.Status__c == 'New Position')
               {

                   task ta = new task();
                   ta.Status = 'In Progress';
                   ta.Subject = 'New Subject';
                   ta.Priority = 'Normal';
                   ta.ActivityDate = System.Today();            
                   ta.Description = 'New Task is Created Related To Position object.';

                   ta.OwnerId = UserInfo.getUserId();         // or pos.OwnerId        // u.Id   (Create Query for user)
                   ta.WhatId = pos.Id;
                   //ta.WhoId = ;

                   taskList.add(ta);

               }






        }


        insert taskList;


    }
    
    
    
    
    
}