force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open - Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Filled</fullName>
            </value>
            <value>
                <fullName>Closed - Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed - Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionTriggerHandlerTest.cls
@isTest
private class PositionTriggerHandlerTest {

    @isTest
    static void test()
    {


        //create Single Data               For Position__c
        Position__c pos = new Position__c();
        pos.Name = 'Test' ;
        pos.Status__c = 'New Position';




        //DML Operation
        Test.StartTest();
        insert pos;
        Test.StopTest();





        //Validate Single Data						// Task is Created Or Not
        Task createdTask = [SELECT Id, Subject, WhatId, OwnerId, Status, Priority
                                    FROM Task
                                    WHERE WhatId = :pos.Id
                                    LIMIT 1];


         System.assert(createdTask != null, 'task is not created.');

         System.assertNotEquals(null, createdTask, 'Task should have been created.');
         //System.assertEquals(1, createdTask.size(), 'Task Is Not created.');





    }

}